
server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/yujinchoi-94/config-repo